tld_country_map = {
"af": "Afghanistan", 
"com.af": "Afghanistan",
"org.af": "Afghanistan",
"net.af": "Afghanistan",
"edu.af": "Afghanistan",
"gov.af": "Afghanistan",
"al": "Albania",
"com.al": "Albania",
"net.al": "Albania",
"org.al": "Albania",
"edu.al": "Albania",
"gov.al": "Albania",
"dz": "Algeria",
"com.dz": "Algeria",
"gov.dz": "Algeria",
"org.dz": "Algeria",
"edu.dz": "Algeria",
"asso.dz": "Algeria",
"pol.dz": "Algeria",
"art.dz": "Algeria",
"net.dz": "Algeria",
"tm.dz": "Algeria",
"soc.dz": "Algeria",
"ad": "Andorra",
"ao": "Angola",
"co.ao": "Angola",
"ed.ao": "Angola",
"og.ao": "Angola",
"pb.ao": "Angola",
"it.ao": "Angola",
"gov.ao": "Angola",
"gv.ao": "Angola",
"ag": "Antigua and Barbuda",
"com.ag": "Antigua and Barbuda",
"co.ag": "Antigua and Barbuda",
"org.ag": "Antigua and Barbuda",
"net.ag": "Antigua and Barbuda",
"nom.ag": "Antigua and Barbuda",
"edu.ag": "Antigua and Barbuda",
"gov.ag": "Antigua and Barbuda",
"ar": "Argentina",
"com.ar": "Argentina",
"net.ar": "Argentina",
"org.ar": "Argentina",
"edu.ar": "Argentina",
"gob.ar": "Argentina",
"gov.ar": "Argentina",
"int.ar": "Argentina",
"mil.ar": "Argentina",
"coop.ar": "Argentina",
"mutual.ar": "Argentina",
"senasa.ar": "Argentina",
"seg.ar": "Argentina",
"tur.ar": "Argentina",
"musica.ar": "Argentina",
"am": "Armenia",
"com.am": "Armenia",
"co.am": "Armenia",
"net.am": "Armenia",
"org.am": "Armenia",
"commune.am": "Armenia",
"au": "Australia",
"com.au": "Australia",
"net.au": "Australia",
"org.au": "Australia",
"edu.au": "Australia",
"gov.au": "Australia",
"asn.au": "Australia",
"id.au": "Australia",
"csiro.au": "Australia",
"act.au": "Australia",
"nsw.au": "Australia",
"nt.au": "Australia",
"qld.au": "Australia",
"sa.au": "Australia",
"tas.au": "Australia",
"vic.au": "Australia",
"wa.au": "Australia",
"qld.gov.au": "Australia",
"sa.gov.au": "Australia",
"act.gov.au": "Australia",
"nsw.gov.au": "Australia",
"nt.gov.au": "Australia",
"tas.gov.au": "Australia",
"vic.gov.au": "Australia",
"wa.gov.au": "Australia",
"at": "Austria",
"ac.at": "Austria",
"gv.at": "Austria",
"co.at": "Austria",
"or.at": "Austria",
"priv.at": "Austria",
"az": "Azerbaijan",
"com.az": "Azerbaijan",
"co.az": "Azerbaijan",
"net.az": "Azerbaijan",
"org.az": "Azerbaijan",
"edu.az": "Azerbaijan",
"gov.az": "Azerbaijan",
"int.az": "Azerbaijan",
"mil.az": "Azerbaijan",
"info.az": "Azerbaijan",
"pp.az": "Azerbaijan",
"name.az": "Azerbaijan",
"pro.az": "Azerbaijan",
"biz.az": "Azerbaijan",
"bs": "Bahamas",
"com.bs": "Bahamas",
"net.bs": "Bahamas",
"org.bs": "Bahamas",
"edu.bs": "Bahamas",
"gov.bs": "Bahamas",
"we.bs": "Bahamas",
"bh": "Bahrain",
"com.bh": "Bahrain",
"edu.bh": "Bahrain",
"org.bh": "Bahrain",
"net.bh": "Bahrain",
"biz.bh": "Bahrain",
"bd": "Bangladesh",
"com.bd": "Bangladesh",
"co.bd": "Bangladesh",
"org.bd": "Bangladesh",
"info.bd": "Bangladesh",
"net.bd": "Bangladesh",
"edu.bd": "Bangladesh",
"ac.bd": "Bangladesh",
"gov.bd": "Bangladesh",
"mil.bd": "Bangladesh",
"tv.bd": "Bangladesh",
"bb": "Barbados",
"com.bb": "Barbados",
"net.bb": "Barbados",
"org.bb": "Barbados",
"gov.bb": "Barbados",
"edu.bb": "Barbados",
"info.bb": "Barbados",
"co.bb": "Barbados",
"biz.bb": "Barbados",
"store.bb": "Barbados",
"tv.bb": "Barbados",
"by": "Belarus",
"com.by": "Belarus",
"gov.by": "Belarus",
"mil.by": "Belarus",
"net.by": "Belarus",
"be": "Belgium",
"ac.be": "Belgium",
"bz": "Belize",
"com.bz": "Belize",
"net.bz": "Belize",
"org.bz": "Belize",
"edu.bz": "Belize",
"gov.bz": "Belize",
"bj": "Benin",
"com.bj": "Benin",
"asso.bj": "Benin",
"org.bj": "Benin",
"gov.bj": "Benin",
"edu.bj": "Benin",
"inf.bj": "Benin",
"bt": "Bhutan",
"com.bt": "Bhutan",
"edu.bt": "Bhutan",
"net.bt": "Bhutan",
"gov.bt": "Bhutan",
"org.bt": "Bhutan",
"bo": "Bolivia",
"third-level": "Bolivia",
"ba": "Bosnia and Herzegovina",
"edu.ba": "Bosnia and Herzegovina",
"gov.ba": "Bosnia and Herzegovina",
"net.ba": "Bosnia and Herzegovina",
"org.ba": "Bosnia and Herzegovina",
"mil.ba": "Bosnia and Herzegovina",
"unsa.ba": "Bosnia and Herzegovina",
"unbi.ba": "Bosnia and Herzegovina",
"co.ba": "Bosnia and Herzegovina",
"com.ba": "Bosnia and Herzegovina",
"bw": "Botswana",
"co.bw": "Botswana",
"org.bw": "Botswana",
"ac.bw": "Botswana",
"net.bw": "Botswana",
"gov.bw": "Botswana",
"shop.bw": "Botswana",
"agric.bw": "Botswana",
"me.bw": "Botswana",
"br": "Brazil",
"com.br": "Brazil",
"net.br": "Brazil",
"org.br": "Brazil",
"gov.br": "Brazil",
"edu.br": "Brazil",
"g12.br": "Brazil",
"mil.br": "Brazil",
"adv.br": "Brazil",
"eng.br": "Brazil",
"med.br": "Brazil",
"pro.br": "Brazil",
"vet.br": "Brazil",
"art.br": "Brazil",
"eco.br": "Brazil",
"ind.br": "Brazil",
"agr.br": "Brazil",
"tur.br": "Brazil",
"app.br": "Brazil",
"dev.br": "Brazil",
"blog.br": "Brazil",
"radio.br": "Brazil",
"tv.br": "Brazil",
"inf.br": "Brazil",
"esp.br": "Brazil",
"rec.br": "Brazil",
"coop.br": "Brazil",
"ong.br": "Brazil",
"b.br": "Brazil",
"jus.br": "Brazil",
"def.br": "Brazil",
"leg.br": "Brazil",
"mp.br": "Brazil",
"tc.br": "Brazil",
"adm.br": "Brazil",
"psi.br": "Brazil",
"fot.br": "Brazil",
"wiki.br": "Brazil",
"zlg.br": "Brazil",
"rio.br": "Brazil",
"sampa.br": "Brazil",
"bsb.br": "Brazil",
"curitiba.br": "Brazil",
"floripa.br": "Brazil",
"sp.br": "Brazil",
"rj.br": "Brazil",
"mg.br": "Brazil",
"rs.br": "Brazil",
"pr.br": "Brazil",
"ba.br": "Brazil",
"pe.br": "Brazil",
"sc.br": "Brazil",
"go.br": "Brazil",
"ce.br": "Brazil",
"pa.br": "Brazil",
"ma.br": "Brazil",
"pb.br": "Brazil",
"rn.br": "Brazil",
"mt.br": "Brazil",
"ms.br": "Brazil",
"am.br": "Brazil",
"ro.br": "Brazil",
"ac.br": "Brazil",
"ap.br": "Brazil",
"to.br": "Brazil",
"rr.br": "Brazil",
"se.br": "Brazil",
"al.br": "Brazil",
"bn": "Brunei",
"com.bn": "Brunei",
"edu.bn": "Brunei",
"gov.bn": "Brunei",
"net.bn": "Brunei",
"org.bn": "Brunei",
"bg": "Bulgaria",
"a.bg": "Bulgaria",
"z.bg": "Bulgaria",
"0.bg": "Bulgaria",
"9.bg": "Bulgaria",
"bf": "Burkina Faso",
"gov.bf": "Burkina Faso",
"bi": "Burundi",
"com.bi": "Burundi",
"co.bi": "Burundi",
"org.bi": "Burundi",
"or.bi": "Burundi",
"edu.bi": "Burundi",
"gov.bi": "Burundi",
"info.bi": "Burundi",
"cv": "Cabo Verde",
"com.cv": "Cabo Verde",
"edu.cv": "Cabo Verde",
"org.cv": "Cabo Verde",
"gov.cv": "Cabo Verde",
"int.cv": "Cabo Verde",
"nome.cv": "Cabo Verde",
"name.cv": "Cabo Verde",
"kh": "Cambodia",
"com.kh": "Cambodia",
"net.kh": "Cambodia",
"org.kh": "Cambodia",
"edu.kh": "Cambodia",
"gov.kh": "Cambodia",
"mil.kh": "Cambodia",
"per.kh": "Cambodia",
"cm": "Cameroon",
"gov.cm": "Cameroon",
"edu.cm": "Cameroon",
"net.cm": "Cameroon",
"org.cm (possible)": "Cameroon",
"ca": "Canada",
"gc.ca": "Canada",
"qc.ca": "Canada",
"ab.ca": "Canada",
"bc.ca": "Canada",
"mb.ca": "Canada",
"nb.ca": "Canada",
"nl.ca": "Canada",
"ns.ca": "Canada",
"nt.ca": "Canada",
"nu.ca": "Canada",
"on.ca": "Canada",
"pei.ca": "Canada",
"sk.ca": "Canada",
"yt.ca": "Canada",
"cf": "Central African Republic",
"td": "Chad",
"com.td": "Chad",
"org.td": "Chad",
"net.td": "Chad",
"info.td": "Chad",
"edu.td": "Chad",
"mil.td": "Chad",
"nat.td": "Chad",
"tourism.td": "Chad",
"sante.td": "Chad",
"agri.td": "Chad",
"ordr.td": "Chad",
"presid.td": "Chad",
"gov.td": "Chad",
"gouv.td": "Chad",
"cl": "Chile",
"gob.cl": "Chile",
"cn": "China",
"com.cn": "China",
"net.cn": "China",
"org.cn": "China",
"edu.cn": "China",
"gov.cn": "China",
"mil.cn": "China",
"com.co": "Colombia",
"km": "Comoros",
"com.km": "Comoros",
"coop.km": "Comoros",
"asso.km": "Comoros",
"nom.km": "Comoros",
"presse.km": "Comoros",
"tm.km": "Comoros",
"medecin.km": "Comoros",
"notaires.km": "Comoros",
"pharmaciens.km": "Comoros",
"veterinaire.km": "Comoros",
"edu.km": "Comoros",
"gouv.km": "Comoros",
"mil.km": "Comoros",
"cg": "Congo-Brazzaville",
"gouv.cg": "Congo-Brazzaville",
"cr": "Costa Rica",
"ac.cr": "Costa Rica",
"co.cr": "Costa Rica",
"ed.cr": "Costa Rica",
"fi.cr": "Costa Rica",
"go.cr": "Costa Rica",
"or.cr": "Costa Rica",
"sa.cr": "Costa Rica",
"hr": "Croatia",
"com.hr": "Croatia",
"iz.hr": "Croatia",
"name.hr": "Croatia",
"cu": "Cuba",
"com.cu": "Cuba",
"co.cu": "Cuba",
"edu.cu": "Cuba",
"net.cu": "Cuba",
"org.cu": "Cuba",
"inf.cu": "Cuba",
"nat.cu": "Cuba",
"sld.cu": "Cuba",
"tur.cu": "Cuba",
"cult.cu": "Cuba",
"gob.cu": "Cuba",
"gov.cu": "Cuba",
"cy": "Cyprus",
"ac.cy": "Cyprus",
"com.cy": "Cyprus",
"biz.cy": "Cyprus",
"net.cy": "Cyprus",
"org.cy": "Cyprus",
"pro.cy": "Cyprus",
"gov.cy": "Cyprus",
"ekloges.cy": "Cyprus",
"tm.cy": "Cyprus",
"ltd.cy": "Cyprus",
"press.cy": "Cyprus",
"mil.cy": "Cyprus",
"cz": "Czechia",
"cd": "Democratic Republic of the Congo",
"com.cd": "Democratic Republic of the Congo",
"net.cd": "Democratic Republic of the Congo",
"org.cd": "Democratic Republic of the Congo",
"edu.cd": "Democratic Republic of the Congo",
"mil.cd": "Democratic Republic of the Congo",
"ac.cd": "Democratic Republic of the Congo",
"dk": "Denmark",
"dj": "Djibouti",
"dm": "Dominica",
"edu.dm": "Dominica",
"gov.dm": "Dominica",
"com.dm": "Dominica",
"net.dm": "Dominica",
"org.dm": "Dominica",
"do": "Dominican Republic",
"com.do": "Dominican Republic",
"net.do": "Dominican Republic",
"org.do": "Dominican Republic",
"edu.do": "Dominican Republic",
"web.do": "Dominican Republic",
"art.do": "Dominican Republic",
"sld.do": "Dominican Republic",
"mil.do": "Dominican Republic",
"gob.do": "Dominican Republic",
"gov.do": "Dominican Republic",
"ec": "Ecuador",
"eg": "Egypt",
"ac.eg": "Egypt",
"com.eg": "Egypt",
"edu.eg": "Egypt",
"egregistry.eg": "Egypt",
"eun.eg": "Egypt",
"gov.eg": "Egypt",
"info.eg": "Egypt",
"mil.eg": "Egypt",
"name.eg": "Egypt",
"net.eg": "Egypt",
"org.eg": "Egypt",
"sci.eg": "Egypt",
"sport.eg": "Egypt",
"tv.eg": "Egypt",
"sv": "El Salvador",
"com.sv": "El Salvador",
"edu.sv": "El Salvador",
"org.sv": "El Salvador",
"red.sv": "El Salvador",
"gob.sv": "El Salvador",
"gov.sv": "El Salvador",
"gq": "Equatorial Guinea",
"com.gq": "Equatorial Guinea",
"org.gq": "Equatorial Guinea",
"net.gq": "Equatorial Guinea",
"edu.gq": "Equatorial Guinea",
"gov.gq": "Equatorial Guinea",
"mil.gq": "Equatorial Guinea",
"univ.gq": "Equatorial Guinea",
"er": "Eritrea",
"com.er": "Eritrea",
"org.er": "Eritrea",
"net.er": "Eritrea",
"edu.er": "Eritrea",
"gov.er": "Eritrea",
"mil.er": "Eritrea",
"ind.er": "Eritrea",
"ee": "Estonia",
"com.ee": "Estonia",
"pri.ee": "Estonia",
"fie.ee": "Estonia",
"med.ee": "Estonia",
"edu.ee": "Estonia",
"lib.ee": "Estonia",
"org.ee": "Estonia",
"sz": "Eswatini",
"co.sz": "Eswatini",
"ac.sz": "Eswatini",
"org.sz": "Eswatini",
"gov.sz": "Eswatini",
"et": "Ethiopia",
"com.et": "Ethiopia",
"net.et": "Ethiopia",
"org.et": "Ethiopia",
"edu.et": "Ethiopia",
"gov.et": "Ethiopia",
"mil.et": "Ethiopia",
"name.et": "Ethiopia",
"info.et": "Ethiopia",
"biz.et": "Ethiopia",
"club.et": "Ethiopia",
"fj": "Fiji",
"ac.fj": "Fiji",
"school.fj": "Fiji",
"gov.fj": "Fiji",
"mil.fj": "Fiji",
"biz.fj": "Fiji",
"com.fj": "Fiji",
"info.fj": "Fiji",
"name.fj": "Fiji",
"net.fj": "Fiji",
"org.fj": "Fiji",
"pro.fj": "Fiji",
"fi": "Finland",
"fr": "France",
"gouv.fr": "France",
"avocat.fr": "France",
"aeroport.fr": "France",
"ga": "Gabon",
"gouv.ga": "Gabon",
"co.ga": "Gabon",
"edu.ga": "Gabon",
"univ.ga": "Gabon",
"net.ga": "Gabon",
"org.ga": "Gabon",
"gm": "Gambia",
"gov.gm": "Gambia",
"edu.gm": "Gambia",
"ge": "Georgia",
"com.ge": "Georgia",
"net.ge": "Georgia",
"org.ge": "Georgia",
"edu.ge": "Georgia",
"school.ge": "Georgia",
"gov.ge": "Georgia",
"mil.ge": "Georgia",
"pvt.ge": "Georgia",
"de": "Germany",
"gh": "Ghana",
"com.gh": "Ghana",
"edu.gh": "Ghana",
"org.gh": "Ghana",
"net.gh": "Ghana",
"mil.gh": "Ghana",
"gov.gh": "Ghana",
"parliament.gh": "Ghana",
"isoc.gh": "Ghana",
"nic.gh": "Ghana",
"cocobod.gh": "Ghana",
"techgov.gh": "Ghana",
"yellowpages.gh": "Ghana",
"gr": "Greece",
"com.gr": "Greece",
"co.gr": "Greece",
"net.gr": "Greece",
"org.gr": "Greece",
"edu.gr": "Greece",
"sch.gr": "Greece",
"gov.gr": "Greece",
"gouv.gr": "Greece",
"mil.gr": "Greece",
"mod.gr": "Greece",
"gd": "Grenada",
"gt": "Guatemala",
"com.gt": "Guatemala",
"net.gt": "Guatemala",
"org.gt": "Guatemala",
"edu.gt": "Guatemala",
"gob.gt": "Guatemala",
"mil.gt": "Guatemala",
"ind.gt": "Guatemala",
"gn": "Guinea",
"com.gn": "Guinea",
"org.gn": "Guinea",
"gov.gn": "Guinea",
"edu.gn": "Guinea",
"net.gn": "Guinea",
"gw": "Guinea-Bissau",
"gy": "Guyana",
"com.gy": "Guyana",
"co.gy": "Guyana",
"org.gy": "Guyana",
"net.gy": "Guyana",
"ht": "Haiti",
"com.ht": "Haiti",
"net.ht": "Haiti",
"org.ht": "Haiti",
"edu.ht": "Haiti",
"info.ht": "Haiti",
"adult.ht": "Haiti",
"art.ht": "Haiti",
"asso.ht": "Haiti",
"firm.ht": "Haiti",
"perso.ht": "Haiti",
"pol.ht": "Haiti",
"pro.ht": "Haiti",
"rel.ht": "Haiti",
"shop.ht": "Haiti",
"hn": "Honduras",
"com.hn": "Honduras",
"net.hn": "Honduras",
"org.hn": "Honduras",
"edu.hn": "Honduras",
"gob.hn": "Honduras",
"gov.hn": "Honduras",
"mil.hn": "Honduras",
"hk": "Hong Kong",
"com.hk": "Hong Kong",
"net.hk": "Hong Kong",
"org.hk": "Hong Kong",
"edu.hk": "Hong Kong",
"gov.hk": "Hong Kong",
"idv.hk": "Hong Kong",
"hu": "Hungary",
"com.hu": "Hungary",
"net.hu": "Hungary",
"org.hu": "Hungary",
"edu.hu": "Hungary",
"gov.hu": "Hungary",
"film.hu": "Hungary",
"games.hu": "Hungary",
"sport.hu": "Hungary",
"info.hu": "Hungary",
"is": "Iceland",
"in": "India",
"co.in": "India",
"com.in": "India",
"firm.in": "India",
"net.in": "India",
"org.in": "India",
"gen.in": "India",
"ind.in": "India",
"res.in": "India",
"ernet.in": "India",
"gov.in": "India",
"mil.in": "India",
"ac.in": "India",
"edu.in": "India",
"id": "Indonesia",
"ac.id": "Indonesia",
"co.id": "Indonesia",
"web.id": "Indonesia",
"biz.id": "Indonesia",
"my.id": "Indonesia",
"net.id": "Indonesia",
"or.id": "Indonesia",
"sch.id": "Indonesia",
"desa.id": "Indonesia",
"go.id": "Indonesia",
"mil.id": "Indonesia",
"kop.id (cooperative)": "Indonesia",
"ponpes.id": "Indonesia",
"ir": "Iran",
"ac.ir": "Iran",
"co.ir": "Iran",
"gov.ir": "Iran",
"id.ir": "Iran",
"net.ir": "Iran",
"org.ir": "Iran",
"sch.ir": "Iran",
"iq": "Iraq",
"com.iq": "Iraq",
"gov.iq": "Iraq",
"edu.iq": "Iraq",
"net.iq": "Iraq",
"org.iq": "Iraq",
"mil.iq": "Iraq",
"name.iq": "Iraq",
"ie": "Ireland",
"gov.ie": "Ireland",
"post.ie": "Ireland",
"coop.ie": "Ireland",
"aero.ie": "Ireland",
"il": "Israel",
"co.il": "Israel",
"org.il": "Israel",
"net.il": "Israel",
"ac.il": "Israel",
"gov.il": "Israel",
"idf.il": "Israel",
"muni.il": "Israel",
"it": "Italy",
"esteri.it": "Italy",
"province.it": "Italy",
"municipality.province.it": "Italy",
"region.it": "Italy",
"jm": "Jamaica",
"com.jm": "Jamaica",
"net.jm": "Jamaica",
"org.jm": "Jamaica",
"edu.jm": "Jamaica",
"gov.jm": "Jamaica",
"mil.jm": "Jamaica",
"jp": "Japan",
"ac.jp": "Japan",
"ad.jp": "Japan",
"co.jp": "Japan",
"ed.jp": "Japan",
"go.jp": "Japan",
"gr.jp": "Japan",
"lg.jp": "Japan",
"ne.jp": "Japan",
"or.jp": "Japan",
"jo": "Jordan",
"com.jo": "Jordan",
"edu.jo": "Jordan",
"sch.jo": "Jordan",
"net.jo": "Jordan",
"org.jo": "Jordan",
"gov.jo": "Jordan",
"mil.jo": "Jordan",
"per.jo": "Jordan",
"phd.jo": "Jordan",
"kz": "Kazakhstan",
"com.kz": "Kazakhstan",
"edu.kz": "Kazakhstan",
"gov.kz": "Kazakhstan",
"mil.kz": "Kazakhstan",
"net.kz": "Kazakhstan",
"org.kz": "Kazakhstan",
"ke": "Kenya",
"co.ke": "Kenya",
"or.ke": "Kenya",
"ne.ke": "Kenya",
"go.ke": "Kenya",
"ac.ke": "Kenya",
"sc.ke": "Kenya",
"me.ke": "Kenya",
"mobi.ke": "Kenya",
"info.ke": "Kenya",
"ki": "Kiribati",
"com.ki": "Kiribati",
"net.ki": "Kiribati",
"org.ki": "Kiribati",
"biz.ki": "Kiribati",
"gov.ki": "Kiribati",
"edu.ki": "Kiribati",
"info.ki": "Kiribati",
"mob.ki": "Kiribati",
"tel.ki": "Kiribati",
"kw": "Kuwait",
"com.kw": "Kuwait",
"net.kw": "Kuwait",
"org.kw": "Kuwait",
"edu.kw": "Kuwait",
"gov.kw": "Kuwait",
"emb.kw": "Kuwait",
"ind.kw": "Kuwait",
"kg": "Kyrgyzstan",
"com.kg": "Kyrgyzstan",
"org.kg": "Kyrgyzstan",
"net.kg": "Kyrgyzstan",
"edu.kg": "Kyrgyzstan",
"gov.kg": "Kyrgyzstan",
"mil.kg": "Kyrgyzstan",
"la": "Laos",
"lv": "Latvia",
"com.lv": "Latvia",
"edu.lv": "Latvia",
"gov.lv": "Latvia",
"org.lv": "Latvia",
"mil.lv": "Latvia",
"id.lv": "Latvia",
"net.lv": "Latvia",
"asn.lv": "Latvia",
"conf.lv": "Latvia",
"lb": "Lebanon",
"com.lb": "Lebanon",
"edu.lb": "Lebanon",
"gov.lb": "Lebanon",
"net.lb": "Lebanon",
"org.lb": "Lebanon",
"ls": "Lesotho",
"ac.ls": "Lesotho",
"sc.ls": "Lesotho",
"co.ls": "Lesotho",
"org.ls": "Lesotho",
"net.ls": "Lesotho",
"gov.ls": "Lesotho",
"nul.ls": "Lesotho",
"info.ls": "Lesotho",
"biz.ls": "Lesotho",
"lr": "Liberia",
"com.lr": "Liberia",
"edu.lr": "Liberia",
"gov.lr": "Liberia",
"org.lr": "Liberia",
"net.lr": "Liberia",
"ly": "Libya",
"com.ly": "Libya",
"net.ly": "Libya",
"gov.ly": "Libya",
"plc.ly": "Libya",
"edu.ly": "Libya",
"sch.ly": "Libya",
"med.ly": "Libya",
"org.ly": "Libya",
"id.ly": "Libya",
"li": "Liechtenstein",
"lt": "Lithuania",
"lu": "Luxembourg",
"mg": "Madagascar",
"com.mg": "Madagascar",
"org.mg": "Madagascar",
"edu.mg": "Madagascar",
"gov.mg": "Madagascar",
"mil.mg": "Madagascar",
"tm.mg": "Madagascar",
"nom.mg": "Madagascar",
"prd.mg": "Madagascar",
"mw": "Malawi",
"com.mw": "Malawi",
"net.mw": "Malawi",
"org.mw": "Malawi",
"ac.mw": "Malawi",
"gov.mw": "Malawi",
"my": "Malaysia",
"com.my": "Malaysia",
"net.my": "Malaysia",
"org.my": "Malaysia",
"biz.my": "Malaysia",
"edu.my": "Malaysia",
"gov.my": "Malaysia",
"mil.my": "Malaysia",
"name.my": "Malaysia",
"coop.my": "Malaysia",
"mv": "Maldives",
"com.mv": "Maldives",
"org.mv": "Maldives",
"net.mv": "Maldives",
"biz.mv": "Maldives",
"coop.mv": "Maldives",
"edu.mv": "Maldives",
"gov.mv": "Maldives",
"mil.mv": "Maldives",
"aero.mv": "Maldives",
"info.mv": "Maldives",
"int.mv": "Maldives",
"museum.mv": "Maldives",
"name.mv": "Maldives",
"pro.mv": "Maldives",
"ml": "Mali",
"com.ml": "Mali",
"net.ml": "Mali",
"org.ml": "Mali",
"edu.ml": "Mali",
"presse.ml": "Mali",
"gov.ml": "Mali",
"mt": "Malta",
"com.mt": "Malta",
"org.mt": "Malta",
"net.mt": "Malta",
"edu.mt": "Malta",
"gov.mt": "Malta",
"mh": "Marshall Islands",
"N/A": "Marshall Islands",
"mr": "Mauritania",
"gov.mr": "Mauritania",
"org.mr": "Mauritania",
"edu.mr": "Mauritania",
"perso.mr": "Mauritania",
"mu": "Mauritius",
"net.mu": "Mauritius",
"gov.mu": "Mauritius",
"com.mu": "Mauritius",
"co.mu": "Mauritius",
"org.mu": "Mauritius",
"or.mu": "Mauritius",
"edu.mu": "Mauritius",
"ac.mu": "Mauritius",
"mx": "Mexico",
"com.mx": "Mexico",
"net.mx": "Mexico",
"org.mx": "Mexico",
"ngo.mx": "Mexico",
"edu.mx": "Mexico",
"gob.mx": "Mexico",
"fm": "Micronesia",
"com.fm": "Micronesia",
"net.fm": "Micronesia",
"org.fm": "Micronesia",
"md": "Moldova",
"gov.md": "Moldova",
"com.md": "Moldova",
"srl.md": "Moldova",
"sa.md": "Moldova",
"net.md": "Moldova",
"org.md": "Moldova",
"acad.md": "Moldova",
"mc": "Monaco",
"tm.mc": "Monaco",
"asso.mc": "Monaco",
"dentiste.mc": "Monaco",
"consul.mc": "Monaco",
"experts-comptables.mc": "Monaco",
"comptables-agrees.mc": "Monaco",
"architectes.mc": "Monaco",
"avocat.mc": "Monaco",
"notaire.mc": "Monaco",
"mn": "Mongolia",
"gov.mn": "Mongolia",
"edu.mn": "Mongolia",
"org.mn": "Mongolia",
"me": "Montenegro",
"net.me": "Montenegro",
"org.me": "Montenegro",
"co.me": "Montenegro",
"edu.me": "Montenegro",
"ac.me": "Montenegro",
"gov.me": "Montenegro",
"its.me": "Montenegro",
"priv.me": "Montenegro",
"ma": "Morocco",
"gov.ma": "Morocco",
"edu.ma": "Morocco",
"org.ma": "Morocco",
"ac.ma": "Morocco",
"co.ma": "Morocco",
"net.ma": "Morocco",
"its.ma": "Morocco",
"priv.ma": "Morocco",
"mz": "Mozambique",
"co.mz": "Mozambique",
"org.mz": "Mozambique",
"net.mz": "Mozambique",
"gov.mz": "Mozambique",
"edu.mz": "Mozambique",
"ac.mz": "Mozambique",
"adv.mz": "Mozambique",
"mm": "Myanmar",
"com.mm": "Myanmar",
"org.mm": "Myanmar",
"net.mm": "Myanmar",
"gov.mm": "Myanmar",
"edu.mm": "Myanmar",
"ac.mm": "Myanmar",
"name.mm": "Myanmar",
"per.mm": "Myanmar",
"biz.mm": "Myanmar",
"pro.mm": "Myanmar",
"hluttaw.mm": "Myanmar",
"na": "Namibia",
"com.na": "Namibia",
"org.na": "Namibia",
"net.na": "Namibia",
"edu.na": "Namibia",
"ac.na": "Namibia",
"gov.na": "Namibia",
"name.na": "Namibia",
"nr": "Nauru",
"com.nr": "Nauru",
"net.nr": "Nauru",
"org.nr": "Nauru",
"biz.nr": "Nauru",
"info.nr": "Nauru",
"gov.nr": "Nauru",
"edu.nr": "Nauru",
"np": "Nepal",
"com.np": "Nepal",
"coop.np": "Nepal",
"edu.np": "Nepal",
"gov.np": "Nepal",
"info.np": "Nepal",
"mil.np": "Nepal",
"name.np": "Nepal",
"net.np": "Nepal",
"org.np": "Nepal",
"nl": "Netherlands",
"com.nl": "Netherlands",
"nz": "New Zealand",
"ac.nz": "New Zealand",
"co.nz": "New Zealand",
"cri.nz": "New Zealand",
"ge.nz": "New Zealand",
"govt.nz": "New Zealand",
"iwi.nz": "New Zealand",
"maori.nz": "New Zealand",
"net.nz": "New Zealand",
"org.nz": "New Zealand",
"school.nz": "New Zealand",
"mil.nz": "New Zealand",
"ni": "Nicaragua",
"com.ni": "Nicaragua",
"edu.ni": "Nicaragua",
"gob.ni": "Nicaragua",
"info.ni": "Nicaragua",
"mil.ni": "Nicaragua",
"net.ni": "Nicaragua",
"org.ni": "Nicaragua",
"co.ni": "Nicaragua",
"ne": "Niger",
"com.ne": "Niger",
"org.ne": "Niger",
"net.ne": "Niger",
"gov.ne": "Niger",
"ng": "Nigeria",
"com.ng": "Nigeria",
"org.ng": "Nigeria",
"gov.ng": "Nigeria",
"edu.ng": "Nigeria",
"net.ng": "Nigeria",
"kp": "North Korea",
"com.kp": "North Korea",
"edu.kp": "North Korea",
"gov.kp": "North Korea",
"org.kp": "North Korea",
"net.kp": "North Korea",
"aca.kp": "North Korea",
"law.kp": "North Korea",
"rep.kp": "North Korea",
"sca.kp": "North Korea",
"mk": "North Macedonia",
"com.mk": "North Macedonia",
"org.mk": "North Macedonia",
"edu.mk": "North Macedonia",
"gov.mk": "North Macedonia",
"inf.mk": "North Macedonia",
"no": "Norway",
"om": "Oman",
"com.om": "Oman",
"edu.om": "Oman",
"gov.om": "Oman",
"net.om": "Oman",
"med.om": "Oman",
"pk": "Pakistan",
"com.pk": "Pakistan",
"edu.pk": "Pakistan",
"gov.pk": "Pakistan",
"net.pk": "Pakistan",
"org.pk": "Pakistan",
"pw": "Palau",
"com.pw": "Palau",
"org.pw": "Palau",
"net.pw": "Palau",
"edu.pw": "Palau",
"gov.pw": "Palau",
"ps": "Palestine",
"com.ps": "Palestine",
"org.ps": "Palestine",
"edu.ps": "Palestine",
"gov.ps": "Palestine",
"pa": "Panama",
"com.pa": "Panama",
"org.pa": "Panama",
"gob.pa": "Panama",
"edu.pa": "Panama",
"pg": "Papua New Guinea",
"com.pg": "Papua New Guinea",
"org.pg": "Papua New Guinea",
"net.pg": "Papua New Guinea",
"gov.pg": "Papua New Guinea",
"edu.pg": "Papua New Guinea",
"py": "Paraguay",
"com.py": "Paraguay",
"org.py": "Paraguay",
"gov.py": "Paraguay",
"edu.py": "Paraguay",
"pe": "Peru",
"com.pe": "Peru",
"org.pe": "Peru",
"edu.pe": "Peru",
"gob.pe": "Peru",
"mil.pe": "Peru",
"ph": "Philippines",
"com.ph": "Philippines",
"net.ph": "Philippines",
"org.ph": "Philippines",
"gov.ph": "Philippines",
"edu.ph": "Philippines",
"pl": "Poland",
"com.pl": "Poland",
"org.pl": "Poland",
"net.pl": "Poland",
"gov.pl": "Poland",
"edu.pl": "Poland",
"pt": "Portugal",
"com.pt": "Portugal",
"org.pt": "Portugal",
"edu.pt": "Portugal",
"gov.pt": "Portugal",
"qa": "Qatar",
"com.qa": "Qatar",
"edu.qa": "Qatar",
"gov.qa": "Qatar",
"org.qa": "Qatar",
"ro": "Romania",
"com.ro": "Romania",
"org.ro": "Romania",
"edu.ro": "Romania",
"gov.ro": "Romania",
"ru": "Russia",
"com.ru": "Russia",
"org.ru": "Russia",
"net.ru": "Russia",
"gov.ru": "Russia",
"mil.ru": "Russia",
"rw": "Rwanda",
"co.rw": "Rwanda",
"org.rw": "Rwanda",
"ac.rw": "Rwanda",
"gov.rw": "Rwanda",
"kn": "Saint Kitts and Nevis",
"com.kn": "Saint Kitts and Nevis",
"net.kn": "Saint Kitts and Nevis",
"org.kn": "Saint Kitts and Nevis",
"edu.kn": "Saint Kitts and Nevis",
"gov.kn": "Saint Kitts and Nevis",
"lc": "Saint Lucia",
"com.lc": "Saint Lucia",
"net.lc": "Saint Lucia",
"org.lc": "Saint Lucia",
"edu.lc": "Saint Lucia",
"gov.lc": "Saint Lucia",
"vc": "Saint Vincent and the Grenadines",
"com.vc": "Saint Vincent and the Grenadines",
"net.vc": "Saint Vincent and the Grenadines",
"org.vc": "Saint Vincent and the Grenadines",
"edu.vc": "Saint Vincent and the Grenadines",
"gov.vc": "Saint Vincent and the Grenadines",
"ws": "Samoa",
"com.ws": "Samoa",
"net.ws": "Samoa",
"org.ws": "Samoa",
"edu.ws": "Samoa",
"gov.ws": "Samoa",
"sm": "San Marino",
"st": "Sao Tome and Principe",
"com.st": "Sao Tome and Principe",
"net.st": "Sao Tome and Principe",
"org.st": "Sao Tome and Principe",
"edu.st": "Sao Tome and Principe",
"gov.st": "Sao Tome and Principe",
"sa": "Saudi Arabia",
"com.sa": "Saudi Arabia",
"org.sa": "Saudi Arabia",
"gov.sa": "Saudi Arabia",
"edu.sa": "Saudi Arabia",
"sn": "Senegal",
"com.sn": "Senegal",
"org.sn": "Senegal",
"edu.sn": "Senegal",
"gov.sn": "Senegal",
"rs": "Serbia",
"com.rs": "Serbia",
"org.rs": "Serbia",
"edu.rs": "Serbia",
"gov.rs": "Serbia",
"sc": "Seychelles",
"com.sc": "Seychelles",
"net.sc": "Seychelles",
"org.sc": "Seychelles",
"edu.sc": "Seychelles",
"gov.sc": "Seychelles",
"sl": "Sierra Leone",
"com.sl": "Sierra Leone",
"net.sl": "Sierra Leone",
"org.sl": "Sierra Leone",
"edu.sl": "Sierra Leone",
"gov.sl": "Sierra Leone",
"sg": "Singapore",
"com.sg": "Singapore",
"net.sg": "Singapore",
"org.sg": "Singapore",
"edu.sg": "Singapore",
"gov.sg": "Singapore",
"sk": "Slovakia",
"com.sk": "Slovakia",
"edu.sk": "Slovakia",
"org.sk": "Slovakia",
"gov.sk": "Slovakia",
"si": "Slovenia",
"com.si": "Slovenia",
"org.si": "Slovenia",
"edu.si": "Slovenia",
"gov.si": "Slovenia",
"sb": "Solomon Islands",
"com.sb": "Solomon Islands",
"net.sb": "Solomon Islands",
"org.sb": "Solomon Islands",
"edu.sb": "Solomon Islands",
"gov.sb": "Solomon Islands",
"so": "Somalia",
"com.so": "Somalia",
"net.so": "Somalia",
"org.so": "Somalia",
"edu.so": "Somalia",
"gov.so": "Somalia",
"za": "South Africa",
"co.za": "South Africa",
"net.za": "South Africa",
"org.za": "South Africa",
"ac.za": "South Africa",
"gov.za": "South Africa",
"kr": "South Korea",
"ac.kr": "South Korea",
"co.kr": "South Korea",
"ne.kr": "South Korea",
"or.kr": "South Korea",
"re.kr": "South Korea",
"pe.kr": "South Korea",
"go.kr": "South Korea",
"ms.kr": "South Korea",
"hs.kr": "South Korea",
"sc.kr": "South Korea",
"busan.kr": "South Korea",
"seoul.kr": "South Korea",
"ai.kr": "South Korea",
"io.kr": "South Korea",
"it.kr": "South Korea",
"me.kr": "South Korea",
"ss": "South Sudan",
"com.ss": "South Sudan",
"org.ss": "South Sudan",
"net.ss": "South Sudan",
"edu.ss": "South Sudan",
"gov.ss": "South Sudan",
"es": "Spain",
"com.es": "Spain",
"org.es": "Spain",
"gob.es": "Spain",
"edu.es": "Spain",
"lk": "Sri Lanka",
"com.lk": "Sri Lanka",
"org.lk": "Sri Lanka",
"edu.lk": "Sri Lanka",
"gov.lk": "Sri Lanka",
"sd": "Sudan",
"com.sd": "Sudan",
"org.sd": "Sudan",
"edu.sd": "Sudan",
"gov.sd": "Sudan",
"sr": "Suriname",
"com.sr": "Suriname",
"net.sr": "Suriname",
"org.sr": "Suriname",
"edu.sr": "Suriname",
"gov.sr": "Suriname",
"se": "Sweden",
"ch": "Switzerland",
"sy": "Syria",
"com.sy": "Syria",
"edu.sy": "Syria",
"gov.sy": "Syria",
"net.sy": "Syria",
"org.sy": "Syria",
"tj": "Tajikistan",
"com.tj": "Tajikistan",
"net.tj": "Tajikistan",
"org.tj": "Tajikistan",
"edu.tj": "Tajikistan",
"gov.tj": "Tajikistan",
"tz": "Tanzania",
"co.tz": "Tanzania",
"or.tz": "Tanzania",
"ac.tz": "Tanzania",
"go.tz": "Tanzania",
"th": "Thailand",
"co.th": "Thailand",
"ac.th": "Thailand",
"go.th": "Thailand",
"in.th": "Thailand",
"or.th": "Thailand",
"tl": "Timor-Leste",
"gov.tl": "Timor-Leste",
"edu.tl": "Timor-Leste",
"tg": "Togo",
"com.tg": "Togo",
"org.tg": "Togo",
"edu.tg": "Togo",
"gov.tg": "Togo",
"to": "Tonga",
"gov.to": "Tonga",
"tt": "Trinidad and Tobago",
"co.tt": "Trinidad and Tobago",
"org.tt": "Trinidad and Tobago",
"edu.tt": "Trinidad and Tobago",
"gov.tt": "Trinidad and Tobago",
"tn": "Tunisia",
"com.tn": "Tunisia",
"org.tn": "Tunisia",
"edu.tn": "Tunisia",
"gov.tn": "Tunisia",
"tr": "Turkey",
"com.tr": "Turkey",
"org.tr": "Turkey",
"edu.tr": "Turkey",
"gov.tr": "Turkey",
"net.tr": "Turkey",
"tm": "Turkmenistan",
"com.tm": "Turkmenistan",
"org.tm": "Turkmenistan",
"edu.tm": "Turkmenistan",
"gov.tm": "Turkmenistan",
"ug": "Uganda",
"co.ug": "Uganda",
"or.ug": "Uganda",
"ac.ug": "Uganda",
"go.ug": "Uganda",
"ua": "Ukraine",
"com.ua": "Ukraine",
"org.ua": "Ukraine",
"edu.ua": "Ukraine",
"gov.ua": "Ukraine",
"ae": "United Arab Emirates",
"com.ae": "United Arab Emirates",
"net.ae": "United Arab Emirates",
"org.ae": "United Arab Emirates",
"gov.ae": "United Arab Emirates",
"mil.ae": "United Arab Emirates",
"uk": "United Kingdom",
"co.uk": "United Kingdom",
"org.uk": "United Kingdom",
"net.uk": "United Kingdom",
"ac.uk": "United Kingdom",
"gov.uk": "United Kingdom",
"us": "United States",
"com.us": "United States",
"org.us": "United States",
"edu.us": "United States",
"gov.us": "United States",
"mil.us": "United States",
"ak.us": "United States",
"al.us": "United States",
"ar.us": "United States",
"as.us": "United States",
"az.us": "United States",
"ca.us": "United States",
"co.us": "United States",
"ct.us": "United States",
"dc.us": "United States",
"de.us": "United States",
"fl.us": "United States",
"ga.us": "United States",
"gu.us": "United States",
"hi.us": "United States",
"ia.us": "United States",
"id.us": "United States",
"il.us": "United States",
"in.us": "United States",
"ks.us": "United States",
"ky.us": "United States",
"la.us": "United States",
"ma.us": "United States",
"md.us": "United States",
"me.us": "United States",
"mi.us": "United States",
"mn.us": "United States",
"mo.us": "United States",
"ms.us": "United States",
"mt.us": "United States",
"nc.us": "United States",
"nd.us": "United States",
"ne.us": "United States",
"nh.us": "United States",
"nj.us": "United States",
"nm.us": "United States",
"nv.us": "United States",
"ny.us": "United States",
"oh.us": "United States",
"ok.us": "United States",
"or.us": "United States",
"pa.us": "United States",
"pr.us": "United States",
"ri.us": "United States",
"sc.us": "United States",
"sd.us": "United States",
"tn.us": "United States",
"tx.us": "United States",
"ut.us": "United States",
"va.us": "United States",
"vi.us": "United States",
"vt.us": "United States",
"wa.us": "United States",
"wi.us": "United States",
"wv.us": "United States",
"wy.us": "United States",
"uy": "Uruguay",
"com.uy": "Uruguay",
"org.uy": "Uruguay",
"edu.uy": "Uruguay",
"gub.uy": "Uruguay",
"uz": "Uzbekistan",
"com.uz": "Uzbekistan",
"org.uz": "Uzbekistan",
"edu.uz": "Uzbekistan",
"gov.uz": "Uzbekistan",
"vu": "Vanuatu",
"com.vu": "Vanuatu",
"net.vu": "Vanuatu",
"org.vu": "Vanuatu",
"edu.vu": "Vanuatu",
"gov.vu": "Vanuatu",
"va": "Vatican",
"ve": "Venezuela",
"com.ve": "Venezuela",
"org.ve": "Venezuela",
"gob.ve": "Venezuela",
"edu.ve": "Venezuela",
"vn": "Vietnam",
"com.vn": "Vietnam",
"net.vn": "Vietnam",
"org.vn": "Vietnam",
"edu.vn": "Vietnam",
"gov.vn": "Vietnam",
"ye": "Yemen",
"com.ye": "Yemen",
"net.ye": "Yemen",
"org.ye": "Yemen",
"edu.ye": "Yemen",
"gov.ye": "Yemen",
"zm": "Zambia",
"com.zm": "Zambia",
"org.zm": "Zambia",
"edu.zm": "Zambia",
"gov.zm": "Zambia",
"zw": "Zimbabwe",
"co.zw": "Zimbabwe",
"org.zw": "Zimbabwe",
"ac.zw": "Zimbabwe",
"gov.zw": "Zimbabwe"
}